




.build/uno/src/manipulation.cpp : src/manipulation.ino
	@mkdir -p .build/uno/src
	@echo [93msrc/manipulation.ino[0m
	@/usr/bin/ino preproc  -o $@ $^


all : .build/uno/src/manipulation.cpp
	@true

